### ISSUE TITLE
NPM release?

### ISSUE THREAD

**Issue by saschagehlich** [GreyRook/pixi-svg-graphics#14]
Just found your fork of my pixi-svg-graphics repository - nice job! I'm currently working on a project that could re-use this plugin and your additions could be very helpful. I'd like to release this on NPM, and since I'm currently the owner of the pixi-svg-graphics module, I'd like to suggest adding you as a contributor so you can publish a new version of the package. Another suggestion would be to create a merge request to my repository and I publish it to NPM.

**Comment by saschagehlich** [comment]
I just noticed it's already released as `pixi-vector-graphics` - you should update the readme then :)

**Comment by FlorianLudwig** [comment]
@saschagehlich thank you for bringing this up to my attention!

I updated the README :+1: 

Oh, and let us know what you think of our rewrite of your library!
