### ISSUE TITLE
cannot install with npm

### ISSUE THREAD

**Issue by baptistebriel** [GreyRook/pixi-svg-graphics#6]
Hi there, I just got an error from a fresh npm install:

`Error: Cannot find module 'PIXI' from '/node_modules/pixi-svg-graphics/src'`

Looks like I can't use the module because `require('PIXI')` should actually be `require('pixi.js')`

Updating this line fixed the issue for me!

**Comment by FlorianLudwig** [comment]
@baptistebriel Can you please provide the exact steps you did to reproduce this?

**Comment by baptistebriel** [comment]
Just a regular `npm i pixi-svg-graphics`, then `import graphics from 'pixi-svg-graphics'` throwed this error.

I think it's just because you're not using the [official npm repo](https://www.npmjs.com/package/pixi.js) for pixi.js.

**Comment by FlorianLudwig** [comment]
the npm package `pixi-svg-graphics` is not this `pixi-svg-graphics` :O
